version: '2.17.2'

services:
  public_api:
    container_name: public_api
    build: ./public_api
    env_file: docker.env
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    command: sh ./run-app.sh

  private_api:
    container_name: private_api
    build: ./private_api
    env_file: docker.env
    command: sh ./run-app.sh
  
  database:
    container_name: database
    image: postgres:13
    env_file: docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2022-07-08T00-05-23Z.fips
    expose:
      - 9000
      - 9001
    command: server /data --console-address ":9001"

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: nginx-debug -g "daemon off;"

